# This profile uses the docker-compose DNS names and is activated for the default docker-compose build

spring:
  rabbitmq:
    host: mls-amqp
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass
application:
  geocoder:
    priority: 1
  poi:
    sources:
      '[file:/config/pois/ehs.json]': EHS
      '[file:/config/pois/hospitals.json]':
      '[file:/config/pois/wrk.json]':
logging:
  config: /config/log-docker.xml
  level:
    root: info
    at.wrk.fmd.mls: debug
