spring:
  rabbitmq:
    host: localhost
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass
application:
  geocoder:
    priority: 1
  poi:
    sources:
      '[pois/ehs.json]': EHS
      '[pois/hospitals.json]':
      '[pois/wrk.json]':
logging:
  level:
    root: info
    at.wrk.fmd.mls: debug
