# This profile uses the docker-compose DNS names and is activated for the default docker-compose build
# Copy it to application-docker.yml and set the Google Maps API key

spring:
  rabbitmq:
    host: mls-amqp
    username: mls-rabbitmq-user
    password: mls-rabbitmq-pass
application:
  geocoder:
    name: gmaps
    priority: 3
  gmaps:
    api-key: !!REQUIRED!!
logging:
  config: /config/log-docker.xml
  level:
    root: info
    at.wrk.fmd.mls: debug
