name: Deploy geocoding Maven artifacts

on:
  push:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/maven-deploy-geocoding.yml
      - geocoding-api/**
      - geocoding-worker/**
      - pom.xml

jobs:
  deploy:
    uses: wrk-fmd/mls-packages/.github/workflows/maven-deploy.yml@main
    secrets:
      token: ${{ secrets.MLS_PACKAGES_TOKEN }}
